Workflow updates (#13)
* fix: update GitHub token secrets in draft-main-pr workflow

* fix: disable fail-fast in tests workflow

* feat: enhance auto-merge workflow to trigger release on successful PR merge

* feat: update draft release workflow to trigger on repository dispatch for PR merges

* fix: clean up version bump script and ensure consistent formatting

* feat: add repository dispatch trigger for PR merges and refine job conditions in pack-package workflow

* fix: update test workflow to skip runs for specific PR branch conditions

diff --git a/.github/workflows/draft-main-pr.yml b/.github/workflows/draft-main-pr.yml
--- a/.github/workflows/draft-main-pr.yml
+++ b/.github/workflows/draft-main-pr.yml
@@ -70,27 +70,27 @@ jobs:
 
       - name: Determine next semantic version for release
         run: |
-            LATEST_TAG=${{ env.CURRENT_VERSION }}
-            if [ -z "$LATEST_TAG" ]; then
-                LATEST_TAG="v${{ env.PACKAGE_VERSION }}"
-            fi
-            
-            if [[ $LATEST_TAG =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(.*)$ ]]; then
-            MAJOR=${BASH_REMATCH[1]}
-            MINOR=${BASH_REMATCH[2]}
-            PATCH=${BASH_REMATCH[3]}
-            else
-            echo "Invalid version format. Expected format: MAJOR.MINOR.PATCH"
-            exit 1
-            fi
-            # if env.BUMP_VERSION == 'false', dont increase patch by 1 else do
-            if [ "${{ env.BUMP_VERSION }}" == 'false' ]; then
-              PATCH=$PATCH
-            else
-              PATCH=$((PATCH + 1))
-            fi
-            NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
-            echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV   
+          LATEST_TAG=${{ env.CURRENT_VERSION }}
+          if [ -z "$LATEST_TAG" ]; then
+              LATEST_TAG="v${{ env.PACKAGE_VERSION }}"
+          fi
+
+          if [[ $LATEST_TAG =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(.*)$ ]]; then
+          MAJOR=${BASH_REMATCH[1]}
+          MINOR=${BASH_REMATCH[2]}
+          PATCH=${BASH_REMATCH[3]}
+          else
+          echo "Invalid version format. Expected format: MAJOR.MINOR.PATCH"
+          exit 1
+          fi
+          # if env.BUMP_VERSION == 'false', dont increase patch by 1 else do
+          if [ "${{ env.BUMP_VERSION }}" == 'false' ]; then
+            PATCH=$PATCH
+          else
+            PATCH=$((PATCH + 1))
+          fi
+          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
+          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
 
       - name: Check if PR already exists
         id: check_pr
@@ -136,36 +136,36 @@ jobs:
       - name: Bump version number (patch increment)
         if: env.BUMP_VERSION == 'true' && env.NEW_COMMITS == 'true'
         run: |
-            LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
-            if [ -z "$LATEST_TAG" ]; then
-                LATEST_TAG="v0.0.0"
-            fi
-            
-            if [[ $LATEST_TAG =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(.*)$ ]]; then
-            MAJOR=${BASH_REMATCH[1]}
-            MINOR=${BASH_REMATCH[2]}
-            PATCH=${BASH_REMATCH[3]}
-            else
-            echo "Invalid version format. Expected format: MAJOR.MINOR.PATCH"
-            exit 1
-            fi
-            PATCH=$((PATCH + 1))
-            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
-          
-            jq --arg NEW_VERSION "$NEW_VERSION" '.version = $NEW_VERSION' package.json > package.tmp && mv package.tmp package.json
-            
-            echo "Updated version in package.json to $NEW_VERSION"
-            git config --global user.name 'github-actions[bot]'
-            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-            git add package.json
-            git commit -m "chore: bump version number on PR to main"
+          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
+          if [ -z "$LATEST_TAG" ]; then
+              LATEST_TAG="v0.0.0"
+          fi
+
+          if [[ $LATEST_TAG =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(.*)$ ]]; then
+          MAJOR=${BASH_REMATCH[1]}
+          MINOR=${BASH_REMATCH[2]}
+          PATCH=${BASH_REMATCH[3]}
+          else
+          echo "Invalid version format. Expected format: MAJOR.MINOR.PATCH"
+          exit 1
+          fi
+          PATCH=$((PATCH + 1))
+          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
+
+          jq --arg NEW_VERSION "$NEW_VERSION" '.version = $NEW_VERSION' package.json > package.tmp && mv package.tmp package.json
+
+          echo "Updated version in package.json to $NEW_VERSION"
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          git add package.json
+          git commit -m "chore: bump version number on PR to main"
 
       - name: Create or update branch
         if: env.BUMP_VERSION == 'true' && env.NEW_COMMITS == 'true'
         run: |
           git checkout -b bump-version-branch || git checkout bump-version-branch
           git pull origin bump-version-branch || echo "Branch does not exist remotely."
-      
+
       - name: Push changes to remote
         if: env.BUMP_VERSION == 'true' && env.NEW_COMMITS == 'true'
         run: |
@@ -189,7 +189,7 @@ jobs:
           gh pr merge $PR_NUMBER --admin --squash --delete-branch
         env:
           GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  
+          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
 
       - name: Create or update draft pull request
         if: env.NEW_COMMITS == 'true'
